services:
  - type: web
    name: fastapi-app
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port 10000
    runtime: python
    region: oregon
